#!/usr/bin/env bash
# Install HAproxy
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y update
sudo apt-get -y install haproxy=1.8.\*
echo "backend web-backend
balance roundrobin
server 1237-web-01 34.73.95.63:80 check
server 1237-web-02 54.242.72.84:80 check
frontend http
bind *:80
mode http
default_backend web-backend
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
