#!/usr/bin/env bash
# Script to set http header
sudo apt update
sudo apt -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.6 -y
sudo apt update
sudo apt install -y haproxy=1.6.\*
lb_config="\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 1237-web-01 34.73.95.63:80 check\n\tserver 1237-web-02 54.242.72.84:80 check\n"
echo -e "$lb_config" | sudo tee --append /etc/haproxy/haproxy.cfg
sudo service haproxy restart
