#!/usr/bin/env bash
# Displays "Holberton School" 10 times, but for the 9th iteration.
i=1
while [ $i -le 10 ]
do
	if [ $i -eq 9 ]; then
		echo "Holberton School"
		echo "Hi"
	else
		echo "Holberton School"
	fi
	((i++))
done
