#!/usr/bin/env bash
# Write a Bash script that gives you information about the holbertonschool file.
# if the file exists, does not exist, file exists, file is empty, holbertonschool file is empty.
# file is not empty, file is a regular file, file is not a regular file.
file="holbertonschool"
if [ -e "$file" ]; then
	echo "$file file exists"
	if [ -s "$file" ]; then
		echo "$file file is not empty"
	else
		echo "$file file is empty"
	fi
	if [ -f "$file" ]; then
		echo "$file is a regular file"
	fi
else
	echo "$file file does not exist"
fi
